-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  church_id uuid NOT NULL,
  entity text NOT NULL CHECK (entity = ANY (ARRAY['member'::text, 'role'::text, 'congregation'::text])),
  entity_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text])),
  changes_before jsonb,
  changes_after jsonb,
  ip text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.calendar_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  title text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['Programação'::text, 'Evento'::text, 'Encontro'::text, 'Reunião'::text])),
  description text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  is_recurring boolean DEFAULT false,
  recurrence_pattern text CHECK (recurrence_pattern = ANY (ARRAY['weekly'::text, 'monthly'::text, 'custom'::text])),
  recurrence_end_date timestamp with time zone,
  location text,
  congregation_id uuid,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'postponed'::text])),
  group_id uuid,
  responsible_member_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  recurrence_time time without time zone,
  recurrence_duration_minutes integer,
  recurrence_day_of_week integer CHECK (recurrence_day_of_week >= 0 AND recurrence_day_of_week <= 6),
  recurrence_day_of_month integer CHECK (recurrence_day_of_month >= 1 AND recurrence_day_of_month <= 31),
  recurrence_week_of_month integer CHECK (recurrence_week_of_month >= '-1'::integer AND recurrence_week_of_month <= 4),
  CONSTRAINT calendar_items_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_items_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id) ON DELETE CASCADE,
  CONSTRAINT calendar_items_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id) ON DELETE SET NULL,
  CONSTRAINT calendar_items_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE SET NULL,
  CONSTRAINT calendar_items_responsible_member_id_fkey FOREIGN KEY (responsible_member_id) REFERENCES public.members(id) ON DELETE SET NULL,
  CONSTRAINT calendar_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.calendar_participants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  calendar_item_id uuid NOT NULL,
  member_id uuid,
  guest_name character varying,
  guest_email character varying,
  guest_phone character varying,
  guest_whatsapp character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendar_participants_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_participants_calendar_item_id_fkey FOREIGN KEY (calendar_item_id) REFERENCES public.calendar_items(id) ON DELETE CASCADE,
  CONSTRAINT calendar_participants_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE SET NULL
);
CREATE TABLE public.churches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  denomination text NOT NULL,
  address text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  cnpj character varying NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  email_church character varying,
  phone_church character varying,
  stripe_customer_id character varying,
  stripe_subscription_id character varying,
  subscription_status character varying CHECK (subscription_status IS NULL OR (subscription_status::text = ANY (ARRAY['active'::character varying, 'canceled'::character varying, 'past_due'::character varying, 'unpaid'::character varying, 'incomplete'::character varying, 'incomplete_expired'::character varying, 'trialing'::character varying, 'paused'::character varying]::text[]))),
  plan_type character varying CHECK (plan_type IS NULL OR (plan_type::text = ANY (ARRAY['100'::character varying, '200'::character varying, '500'::character varying, '800'::character varying, 'custom'::character varying]::text[]))),
  subscription_start_date timestamp with time zone,
  subscription_end_date timestamp with time zone,
  subscription_updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT churches_pkey PRIMARY KEY (id),
  CONSTRAINT churches_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.congregations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  name text NOT NULL,
  address text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  leader text,
  phone text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT congregations_pkey PRIMARY KEY (id),
  CONSTRAINT congregations_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id) ON DELETE CASCADE
);
CREATE TABLE public.groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  congregation_id uuid,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['Ministério'::character varying, 'Departamento'::character varying, 'Equipe'::character varying, 'Time'::character varying, 'Comissão'::character varying, 'Célula'::character varying, 'Grupo de Crescimento'::character varying, 'Pequeno Grupo'::character varying, 'Discipulado'::character varying, 'Classe'::character varying, 'Núcleo'::character varying, 'Região'::character varying, 'Grupo'::character varying]::text[])),
  name character varying NOT NULL,
  description text,
  responsible_id uuid,
  status boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT groups_pkey PRIMARY KEY (id),
  CONSTRAINT groups_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id) ON DELETE CASCADE,
  CONSTRAINT groups_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id) ON DELETE SET NULL,
  CONSTRAINT groups_responsible_id_fkey FOREIGN KEY (responsible_id) REFERENCES public.members(id) ON DELETE SET NULL
);
CREATE TABLE public.integration_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  name text NOT NULL,
  birth date,
  gender USER-DEFINED,
  marital_status USER-DEFINED,
  phone text,
  whatsapp text,
  expected_admission_type USER-DEFINED,
  expected_congregation_id uuid,
  mentor_id uuid,
  notes text,
  status USER-DEFINED NOT NULL DEFAULT 'em_progresso'::integration_status_enum,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT integration_members_pkey PRIMARY KEY (id),
  CONSTRAINT integration_members_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT integration_members_expected_congregation_id_fkey FOREIGN KEY (expected_congregation_id) REFERENCES public.congregations(id) ON DELETE SET NULL,
  CONSTRAINT integration_members_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.members(id)
);
CREATE TABLE public.member_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL,
  group_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT member_groups_pkey PRIMARY KEY (id),
  CONSTRAINT member_groups_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE,
  CONSTRAINT member_groups_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE CASCADE
);
CREATE TABLE public.members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  church_id uuid NOT NULL,
  name text NOT NULL,
  birth date NOT NULL,
  gender text CHECK (gender = ANY (ARRAY['Masculino'::text, 'Feminino'::text, 'Outro'::text])),
  marital_status text CHECK (marital_status = ANY (ARRAY['Solteiro'::text, 'Casado'::text, 'Divorciado'::text, 'Viúvo'::text, 'Outro'::text])),
  nationality text,
  document text,
  spouse text,
  address text,
  complement text,
  cep text,
  neighborhood text,
  city text,
  state text,
  phone text,
  whatsapp text,
  email text,
  baptism_date date,
  occupation text,
  admission text,
  admission_date date,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  congregation_id uuid,
  father_name text,
  mother_name text,
  children jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT members_pkey PRIMARY KEY (id),
  CONSTRAINT members_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT members_congregation_id_fkey FOREIGN KEY (congregation_id) REFERENCES public.congregations(id) ON DELETE SET NULL
);
CREATE TABLE public.pending_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL,
  stripe_customer_id character varying NOT NULL,
  stripe_subscription_id character varying NOT NULL,
  plan_type character varying NOT NULL CHECK (plan_type::text = ANY (ARRAY['200'::character varying, '500'::character varying, '800'::character varying, 'custom'::character varying]::text[])),
  subscription_status character varying NOT NULL CHECK (subscription_status::text = ANY (ARRAY['active'::character varying, 'canceled'::character varying, 'past_due'::character varying, 'unpaid'::character varying, 'incomplete'::character varying, 'incomplete_expired'::character varying, 'trialing'::character varying, 'paused'::character varying]::text[])),
  subscription_start_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  CONSTRAINT pending_subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.processed_webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stripe_event_id character varying NOT NULL UNIQUE,
  event_type character varying NOT NULL,
  processed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT processed_webhook_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.public_integration_links (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  max_uses integer CHECK (max_uses IS NULL OR max_uses > 0),
  current_uses integer NOT NULL DEFAULT 0 CHECK (current_uses >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  CONSTRAINT public_integration_links_pkey PRIMARY KEY (id),
  CONSTRAINT public_integration_links_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT public_integration_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.public_registration_links (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  church_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  max_uses integer CHECK (max_uses IS NULL OR max_uses > 0),
  current_uses integer NOT NULL DEFAULT 0 CHECK (current_uses >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  default_congregation_id uuid,
  notes text,
  CONSTRAINT public_registration_links_pkey PRIMARY KEY (id),
  CONSTRAINT public_registration_links_church_id_fkey FOREIGN KEY (church_id) REFERENCES public.churches(id),
  CONSTRAINT public_registration_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT public_registration_links_default_congregation_id_fkey FOREIGN KEY (default_congregation_id) REFERENCES public.congregations(id) ON DELETE SET NULL
);
CREATE TABLE public.waitlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  phone character varying NOT NULL,
  church_name character varying NOT NULL,
  city character varying NOT NULL,
  state character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  plan character varying NOT NULL CHECK (plan::text = ANY (ARRAY['200'::character varying, '500'::character varying, '800'::character varying, 'personalizado'::character varying]::text[])),
  message text,
  CONSTRAINT waitlist_pkey PRIMARY KEY (id)
);