import type { TutorialGuide } from '../types';

export const primeirosPassosGuides: TutorialGuide[] = [
  {
    slug: 'pp-01-conhecer-painel',
    title: 'Conhecer o Painel de Relatórios',
    module: 'relatorios',
    role: 'reader',
    route: '/',
    estimatedMinutes: 2,
    tags: ['início', 'dashboard', 'analytics'],
    steps: [
      'Clique em Painel na barra lateral (primeiro item).',
      'Aguarde o carregamento dos gráficos e cards de resumo.',
      'Use o seletor no topo para alternar entre Todas as congregações ou uma Congregação específica.',
      'Role a página para ver demografia, estrutura da igreja, grupos e mapa geográfico.',
      'Para atualizar os dados, clique no botão de atualizar (ícone de refresh).',
    ],
    details: [
      'Os relatórios usam os membros ativos cadastrados no sistema.',
      'Se a igreja ainda não tem membros, os gráficos aparecerão vazios — isso é normal no início.',
      'Para exportar um PDF do painel, use o botão Exportar PDF (disponível quando há dados).',
    ],
    related: ['relatorios-filtrar', 'membros-cadastrar'],
    trailOrder: 1,
  },
  {
    slug: 'pp-02-primeira-congregacao',
    title: 'Cadastrar sua primeira congregação',
    module: 'congregacoes',
    role: 'editor',
    route: '/congregations',
    estimatedMinutes: 3,
    tags: ['início', 'estrutura', 'congregação'],
    steps: [
      'Clique em Congregações na barra lateral.',
      'Clique em Adicionar congregação.',
      'Preencha o nome da congregação (obrigatório).',
      'Informe endereço, cidade e estado — a busca de cidade usa a base do IBGE.',
      '(Opcional) Selecione um líder entre os membros já cadastrados.',
      'Clique em Salvar.',
    ],
    details: [
      'A congregação principal é criada automaticamente com o nome da igreja — você cadastra as demais congregações conforme necessário.',
      'Congregações aparecem depois nos formulários de membros, grupos e calendário.',
      'Se você ainda não tem membros, o campo líder ficará vazio — pode editar depois.',
    ],
    related: ['congregacoes-editar', 'membros-cadastrar'],
    trailOrder: 2,
  },
  {
    slug: 'pp-03-primeiro-membro',
    title: 'Cadastrar seu primeiro membro',
    module: 'membros',
    role: 'editor',
    route: '/members',
    estimatedMinutes: 3,
    tags: ['início', 'cadastro', 'membro'],
    steps: [
      'Clique em Membros na barra lateral.',
      'Clique em Adicionar membro.',
      'Preencha pelo menos o nome completo e os campos marcados como obrigatórios (*).',
      'Selecione a congregação à qual o membro pertence.',
      'Revise contatos (telefone, e-mail) se disponíveis.',
      'Clique em Salvar.',
    ],
    details: [
      'Campos de endereço podem ser preenchidos automaticamente ao digitar o CEP.',
      'O plano da igreja define um limite de membros — o contador aparece no topo do app.',
      'Membros inativos continuam no sistema mas não entram nos relatórios padrão.',
    ],
    related: ['membros-filtrar', 'membros-editar'],
    trailOrder: 3,
  },
  {
    slug: 'pp-04-primeiro-integrante',
    title: 'Registrar um visitante na Integração',
    module: 'integracao',
    role: 'editor',
    route: '/integration',
    estimatedMinutes: 3,
    tags: ['início', 'visitante', 'integração'],
    steps: [
      'Clique em Integração na barra lateral.',
      'Clique em Adicionar integrante.',
      'Preencha nome, data de nascimento e contatos básicos.',
      'Indique a congregação esperada e, se souber, o mentor.',
      'Clique em Salvar.',
    ],
    details: [
      'Integração é o funil antes da membresia formal — use para visitantes e candidatos.',
      'Quando a pessoa estiver pronta, converta em membro pelo guia Converter integrante em membro.',
      'Integrantes não contam no limite de membros do plano até serem convertidos.',
    ],
    related: ['integracao-converter', 'integracao-filtrar'],
    trailOrder: 4,
  },
  {
    slug: 'pp-05-primeiro-grupo',
    title: 'Criar seu primeiro grupo',
    module: 'grupos',
    role: 'editor',
    route: '/groups',
    estimatedMinutes: 3,
    tags: ['início', 'ministério', 'célula', 'grupo'],
    steps: [
      'Clique em Grupos na barra lateral.',
      'Clique em Adicionar grupo (ou botão equivalente com ícone +).',
      'Informe o nome e escolha o tipo (ministério, célula, departamento, etc.).',
      '(Opcional) Associe uma congregação e um responsável (membro).',
      'Clique em Salvar.',
      'Abra o grupo e adicione membros à composição.',
    ],
    details: [
      'O responsável deve ser um membro já cadastrado.',
      'Grupos inativos permanecem no histórico mas não aparecem em filtros padrão.',
      'Grupos alimentam relatórios e filtros do calendário.',
    ],
    related: ['grupos-membros', 'grupos-filtrar'],
    trailOrder: 5,
  },
  {
    slug: 'pp-06-primeiro-evento',
    title: 'Adicionar um evento no Calendário',
    module: 'calendario',
    role: 'editor',
    route: '/calendar',
    estimatedMinutes: 3,
    tags: ['início', 'evento', 'agenda'],
    steps: [
      'Clique em Calendário na barra lateral.',
      'Clique em Novo evento ou clique em um dia vazio no calendário mensal.',
      'Preencha título, tipo, data e, se aplicável, horário.',
      '(Opcional) Associe congregação, grupo ou responsável.',
      'Clique em Salvar.',
    ],
    details: [
      'Use a aba Lista para ver todos os eventos do ano.',
      'Eventos recorrentes podem ser configurados no formulário — edite com cuidado pois alterações podem afetar a série.',
      'O contador de aniversariantes do mês aparece no topo do calendário.',
    ],
    related: ['calendario-filtrar', 'calendario-aniversariantes'],
    trailOrder: 6,
  },
];
